# Generated by Django 2.2 on 2020-04-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogory',
            new_name='Category',
        ),
    ]
